### ISSUE TITLE
Clarify naming convention files

### ISSUE THREAD

**Issue by BrechtPh** [WannesFransen1994/elixir-basics#4]
Make sure that it is clear that the student need to create a file called "student.exs" file with their solution. 
The console is pretty clear that it cant find the "student.exs" file but depending on the grade you'll teach it could form an issue.

**Comment by WannesFransen1994** [comment]
> Make sure that it is clear that the student need to create a file called "student.exs" file with their solution.

I'm afraid that mentioning it every time in the `assignment.md` will clutter the assignment, causing the students to skip / not read a part of it. There's also the issue of an infinite loop if `shared.exs` is not present. Perhaps a more clear error message with `Logger.warn` is an option?

E.g. `Logger.error "Could not find student.exs . Make sure that your file is called \"student.exs\"!"`
Similar error would be applicable if students somehow don't have the `shared.exs` file.
